2024-02-05 14:37:45,130 - process_api - INFO - run schema: "lookup_empty"
2024-02-05 14:37:45,131 - process_api - INFO - run process: "main"
2024-02-05 14:37:45,131 - process_api - INFO - run step: "start"
2024-02-05 14:37:45,131 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-02-05 14:37:45,721 - process_api - INFO - run step: "click_create_button"
2024-02-05 14:37:45,721 - process_api - INFO - perform click on #create
2024-02-05 14:38:15,818 - process_api - ERROR - Message: 

2024-02-05 14:38:15,818 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 79, in perform
    await perform(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\perform.py", line 15, in perform
    element = await get_element(context, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 53, in get_element
    element = wait.until(element_callback(None, {
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-05 14:38:16,057 - process_api - INFO - Task 48f83a53-7b43-4e81-9f9d-3ed7752f5c84 completed in 00:00:30:688
