2024-02-05 14:11:17,307 - process_api - INFO - run schema: "lookup_empty"
2024-02-05 14:11:17,307 - process_api - INFO - run process: "main"
2024-02-05 14:11:17,308 - process_api - INFO - run step: "start"
2024-02-05 14:11:17,308 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-02-05 14:14:46,157 - process_api - INFO - run step: "click_create_button"
2024-02-05 14:14:50,623 - process_api - INFO - perform click on #create
2024-02-05 14:15:20,714 - process_api - ERROR - Message: 

2024-02-05 14:15:20,714 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 79, in perform
    await perform(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\perform.py", line 15, in perform
    element = await get_element(context, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 53, in get_element
    element = wait.until(element_callback(None, {
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-05 14:15:21,122 - process_api - INFO - Task 189ad15f-96a7-45a7-8e50-b99602bdd9a0 completed in 00:04:03:407
