2024-02-05 14:07:04,805 - process_api - INFO - run schema: "lookup_empty"
2024-02-05 14:07:04,805 - process_api - INFO - run process: "main"
2024-02-05 14:07:04,805 - process_api - INFO - run step: "start"
2024-02-05 14:07:04,806 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-02-05 14:07:47,362 - process_api - INFO - run step: "click_create_button"
2024-02-05 14:07:47,362 - process_api - INFO - perform click on #create
2024-02-05 14:08:17,396 - process_api - ERROR - Message: 

2024-02-05 14:08:17,396 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 79, in perform
    await perform(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\perform.py", line 15, in perform
    element = await get_element(context, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 53, in get_element
    element = wait.until(element_callback(None, {
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-05 14:08:17,877 - process_api - INFO - Task de05ed7a-036a-488b-b8da-07634adb9575 completed in 00:01:12:590
