2024-01-29 11:01:13,277 - process_api - INFO - run schema: "file attachments"
2024-01-29 11:01:13,277 - process_api - INFO - run process: "main"
2024-01-29 11:01:13,277 - process_api - INFO - run step: "start"
2024-01-29 11:01:13,277 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-01-29 11:01:13,311 - process_api - INFO - run step: "wait_for_dashboard"
2024-01-29 11:01:13,311 - process_api - INFO - wait for attribute: {'query': '#dashboard-grid', 'attr': 'data-loaded', 'value': 'true'}
2024-01-29 11:01:15,094 - process_api - INFO - run step: "dbl_click_first_row"
2024-01-29 11:01:15,094 - process_api - INFO - perform dbl_click on #dashboard-grid .grid-row:first-child
2024-01-29 11:01:15,456 - process_api - INFO - run step: "wait_for_edit_screen"
2024-01-29 11:01:15,457 - process_api - INFO - wait for element: {'query': 'pragma-action-dialog [data-template=WorkOrderUpdate]'}
2024-01-29 11:01:16,236 - process_api - INFO - run step: "wait_for_overflow_button"
2024-01-29 11:01:16,236 - process_api - INFO - wait for attribute: {'query': '#btnOptions', 'attr': 'status', 'value': 'ready'}
2024-01-29 11:01:46,572 - process_api - ERROR - Message: 

2024-01-29 11:01:46,573 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 58, in get_element
    return wait_for_element(driver, element, wait)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 75, in wait_for_element
    wait.until(element_usable_callback(element))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-01-29 11:01:46,573 - process_api - ERROR - 'NoneType' object has no attribute 'get_attribute'
2024-01-29 11:01:46,573 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  [Previous line repeated 1 more time]
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 53, in attribute
    await wait_for_element_details(api, step, attribute_callback, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 21, in wait_for_element_details
    WebDriverWait(selenium_driver, timeout).until(callback(element, args))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\condition_callbacks\attribute_callback.py", line 6, in _predicate
    value = element.get_attribute(args["attr"])
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

2024-01-29 11:01:46,573 - process_api - INFO - run process: "TC1"
2024-01-29 11:01:46,573 - process_api - INFO - run step: "start"
2024-01-29 11:01:46,573 - process_api - INFO - assert attribute_eq: {'query': "dynamic-crud-toolbar[for='WorkOrderFileAttachmentsGrid'] #propertiesPanel", 'attr': 'tooltip', 'value': 'Properties Panel'}
2024-01-29 11:01:46,573 - process_api - INFO - wait for attribute: {'query': "dynamic-crud-toolbar[for='WorkOrderFileAttachmentsGrid'] #propertiesPanel", 'attr': 'tooltip', 'value': 'Properties Panel', 'operator': 'eq'}
2024-01-29 11:02:18,652 - process_api - ERROR - Message: 

2024-01-29 11:02:18,653 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 51, in get_element
    return await get_element_on_path(driver, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 90, in get_element_on_path
    element = wait.until(light_and_shadow_dom_callback(element, shadow_root, query))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-01-29 11:02:18,653 - process_api - ERROR - 'NoneType' object has no attribute 'get_attribute'
2024-01-29 11:02:18,658 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_assert.py", line 81, in attribute_eq
    await WaitModule.attribute(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 53, in attribute
    await wait_for_element_details(api, step, attribute_callback, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 21, in wait_for_element_details
    WebDriverWait(selenium_driver, timeout).until(callback(element, args))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\condition_callbacks\attribute_callback.py", line 6, in _predicate
    value = element.get_attribute(args["attr"])
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

2024-01-29 11:02:18,658 - process_api - INFO - run process: "TC2"
2024-01-29 11:02:18,659 - process_api - INFO - run step: "start"
2024-01-29 11:02:18,659 - process_api - INFO - perform click on #WorkOrderFileAttachmentsGrid [name=select-all-checkbox]
2024-01-29 11:02:48,761 - process_api - ERROR - Message: 

2024-01-29 11:02:48,767 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 79, in perform
    await perform(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\perform.py", line 15, in perform
    element = await get_element(context, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 51, in get_element
    return await get_element_on_path(driver, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 90, in get_element_on_path
    element = wait.until(light_and_shadow_dom_callback(element, shadow_root, query))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-01-29 11:02:48,777 - process_api - INFO - run process: "TC3"
2024-01-29 11:02:48,777 - process_api - INFO - run step: "start"
2024-01-29 11:02:48,778 - process_api - ERROR - action 'run_script' not found in the imported module 'system'.
2024-01-29 11:02:48,778 - process_api - INFO - run process: "TC4"
2024-01-29 11:02:48,778 - process_api - INFO - run step: "start"
2024-01-29 11:02:48,778 - process_api - ERROR - action 'run_script' not found in the imported module 'system'.
2024-01-29 11:02:49,068 - process_api - INFO - Task cd399997-3c63-400e-99a2-79d8f44bec7d completed in 00:01:35:500
