2024-02-07 07:35:51,864 - process_api - INFO - run schema: "Inline Editing Tests"
2024-02-07 07:35:51,864 - process_api - INFO - run process: "main"
2024-02-07 07:35:51,864 - process_api - INFO - run step: "start"
2024-02-07 07:35:51,864 - process_api - INFO - perform navigate: ${state.server}/#dashboard/SiteType
2024-02-07 07:35:51,907 - process_api - INFO - run step: "wait_till_idle"
2024-02-07 07:35:51,907 - process_api - INFO - wait for idle: {}
2024-02-07 07:36:21,979 - process_api - ERROR - Message: 

2024-02-07 07:36:21,980 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 53, in get_element
    element = wait.until(element_callback(None, {
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-07 07:36:21,984 - process_api - INFO - run process: "lookup_test"
2024-02-07 07:36:21,984 - process_api - INFO - run step: "start"
2024-02-07 07:36:21,984 - process_api - INFO - wait for attribute: {'query': '#dashboard-grid', 'attr': 'status', 'value': 'ready'}
2024-02-07 07:36:22,244 - process_api - INFO - Task 5e8b8320-60dd-4e88-a08e-03553d0455a3 completed in 00:00:30:164
