2024-02-05 12:16:02,751 - process_api - INFO - run schema: "lookup_basic"
2024-02-05 12:16:02,751 - process_api - INFO - run process: "main"
2024-02-05 12:16:02,751 - process_api - INFO - run step: "start"
2024-02-05 12:16:02,751 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-02-05 12:16:02,768 - process_api - INFO - run step: "wait_for_idle_cpu"
2024-02-05 12:16:02,768 - process_api - INFO - wait for idle: {}
2024-02-05 12:16:32,905 - process_api - ERROR - Message: 

2024-02-05 12:16:32,905 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 53, in get_element
    element = wait.until(element_callback(None, {
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-05 12:16:33,156 - process_api - INFO - Task eb7687b8-b224-4a0e-a7b2-dd37e41e4b13 completed in 00:00:30:153
